---
- name: create destination volume and snapmirror
  hosts: "localhost"
  become: no
  gather_facts: no

  collections:
  - awx.awx
  tasks:
  - name: Launch a job template with extra_vars on remote controller instance
    job_launch:
      job_template: "HelloWorld"
      controller_username: admin
      controller_password: Netapp12
      extra_vars:
        var1: "My First Variable"
        var2: "My Second Variable"
        var3: "My Third Variable"
      job_type: run
    register: job
  - name: Wait for job max 120s
    job_wait:
      job_id: "{{ job.id }}"
      timeout: 120
