---
- name: try loopback
  hosts: "localhost"
  become: no
  gather_facts: no

  collections:
  - awx.awx
  tasks:
  - name: Launch a job template with extra_vars on remote controller instance
    job_launch:
      job_template: "HelloWorld"
      controller_host: 172.16.50.1:80
      controller_oauthtoken: CjDw4KIEobnXcWMfz40Ozc3ogHJVnR
      validate_certs: no
      extra_vars:
        var1: "My First Variable"
        var2: "My Second Variable"
        var3: "My Third Variable"
      job_type: run
    register: job
  - name: Wait for job max 120s
    job_wait:
      job_id: "{{ job.id }}"
      timeout: 120
